name: Anudan App Roll Back 

on:
  workflow_dispatch:
 
   
jobs:  

  #https://github.com/marketplace/actions/remote-ssh-commands
  Anudan-Roll-Back-To-Previous-Version:
    runs-on: ubuntu-latest
    if: ${{ github.actor }} == 'karni-prabhu' 
    name: App Roll Back
    steps:   
      - name: checkout Anudan_backup_Recovery.js file from release repo    
        uses: actions/checkout@v2
        with:
            repository: anudan-org/release   
            token: ${{ secrets.MY_PAT }}   
      - name: copying Anudan_backup_Recovery.js file to remote server 
        uses: burnett01/rsync-deployments@4.1
        with:
              switches: -avzr -q
              path: Anudan_backup_Recovery.js
              remote_path: /home/anudan/github
              remote_host: ${{ secrets.HOST_QA }}
              remote_port: ${{ secrets.SSH_PORT }}
              remote_user: ${{ secrets.SSH_USER }}
              remote_key: ${{ secrets.SSH_DEPLOY_KEY }} 
      - name: Roll Back To Previous Version
        uses: fifsky/ssh-action@master
        if: ${{ env.var }} == 'yes' 
        with:
          command: |
            cd /home/anudan/github
            BuildNO=`cat Anudan_backup_Recovery.js | cut -d "," -f1 | cut -d ":" -f2 | sed 's/"//g' | sed 's/}//g'`
            /home/anudan/github/s3cmd/s3cmd-2.0.1/s3cmd --recursive --force get s3://anudan-certified-uat-artifacts-test/"$BuildNO"/
            ls -a
            #rm Anudan_backup_Recovery.js
          host: ${{ secrets.HOST_QA }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }} 

  Notify-on-email:
    runs-on: ubuntu-latest
    if: always()
    needs: [ Anudan-Roll-Back-To-Previous-Version ]
    name: Notify Via Email
    steps:
      - name: Send mail
        if: always()
        uses: wadeww/send-email-action@master
        with:
          server_address: smtp.gmail.com
          port: ${{ secrets.SMTP_SERVER_PORT }}
          username: ${{ secrets.AUTH_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Anudan App Roll Back
          body: Organization Name/Repository - ${{github.repository}} 
                
                
              

                1. App Roll Back - ${{needs.Anudan-Roll-Back-To-Previous-Version.result}} 

                

          to: ${{ secrets.TO_ADDRESSES }} 
          from: ${{ secrets.FROM_ADDRESS }}                
