name: Anudan User Data Roll Back 

on:
  workflow_dispatch:
 
   
jobs:  

  #https://github.com/marketplace/actions/remote-ssh-commands
  Anudan-Roll-Back-To-Previous-Version:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' 
    name: Anudan User Data Roll Back
    steps:       
      - name: Roll Back User Data To Previous Version
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd /home/anudan/github
            ls -a
            #!/bin/bash
            cd /home/anudan/github
            BuildNO="Anudan-application-no"
            /home/anudan/github/s3cmd/s3cmd-2.0.1/s3cmd --recursive --force get s3://anudan-certified-uat-artifacts-test/"$BuildNO"/
          host: ${{ secrets.HOST_QA }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_DEPLOY_KEY }} 