name: DEV Release Version

on:
  workflow_dispatch:
  #push:
   #branches: [ dev ]
  #pull_request:
   # branches: [ master ]
  #schedule:
   # - cron:'0/5 * * * *' 

jobs:
  # this block of code will create Dev release version for Dev remote server. 
  Dev-Release-version:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/dev' 
      name: Dev Release version
      steps:
        - uses: actions/checkout@v2
          with:
            repository: anudan-org/release   
            token: ${{ secrets.MY_PAT }}
            ref: master
        - name: setup variable
          run: | 
             echo "major=`cat release.json | cut -d "," -f4 | cut -d ":" -f2 | sed 's/"//g' | sed 's/}//g'`" >> $GITHUB_ENV  
             echo "minor=`cat release.json | cut -d "," -f5 | cut -d ":" -f2 | sed 's/"//g' | sed 's/}//g'`" >> $GITHUB_ENV
        - name: release version creating for Dev
          run: | 
             echo '{"releaseCandidate":"${{env.major}}.${{env.minor}}.${{ github.run_number }}"}' > Dev_release.json 
        - name: Commit files
          run: |
            git config --local user.email "admin@anudan.org"
            git config --local user.name "${GITHUB_ACTOR}"
            git add .
            git commit -m "File updated automatically by ${GITHUB_ACTOR} action." 
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.MY_PAT }}
            repository: anudan-org/release 
            branch: master  

      
