name: DEV Rlease Version

on:
  workflow_dispatch:
  #push:
   #branches: [ dev ]
  #pull_request:
   # branches: [ master ]
  #schedule:
   # - cron:'0/5 * * * *' 

jobs:
  # this block of code will create Dev release version for Dev remote server. 
  Dev-Release-version:
      runs-on: ubuntu-latest
      if: github.ref == 'refs/heads/dev' 
      name: Dev Rlease version
      steps:
        - uses: actions/checkout@v2
          with:
            repository: anudan-org/release   
            token: ${{ secrets.MY_PAT }}
            ref: master
        - name: release version creating for Dev
          run: | 
             ls -lrt
             pwd
             version=`cat CustomRelease.json| cut -d "," -f1 | cut -d ":" -f2 | sed 's/"//g' | sed 's/}//g'`
             echo "version=`cat CustomRelease.json| cut -d "," -f1 | cut -d ":" -f2 | sed 's/"//g' | sed 's/}//g'`" >> $GITHUB_ENV
             echo '{"releaseCandidate":"Dev R-${{ version }}.${MajorRelease}.${{ github.run_number }}"}' > Dev_release.json 
             echo "hii_no: $version"
             ls -lrt
        - name: Commit files
          run: |
            git config --local user.email "admin@anudan.org"
            git config --local user.name "${GITHUB_ACTOR}"
            git add .
            git commit -m "this file is updated by github/action" 
        - name: Push changes
          uses: ad-m/github-push-action@master
          with:
            github_token: ${{ secrets.MY_PAT }}
            repository: anudan-org/release 
            branch: master  

      